### PR TITLE
docs(week4): Report for week 4

### PR DESCRIPTION
**Pull request by soham4abc**
## Project

Rest API

### Changes

Documentation update for week 4

Please do have a look

@shaheemazmalmmd @GMishx @avinal

### CODE REVIEW

**Comment by shaheemazmalmmd** [comment]
@soham4abc can you please squash the commits to one.

**Comment by soham4abc** [comment]
continued on #160

**Comment by soham4abc** [comment]
> 

Sure sir, 

I was just unsure of squashing the `Merge branch 'main' into soham4abc/week` commit to my original commit.

I generally use the `git rebase -i HEAD~2` command... but for this I was unsure to squash which commits so that it doesnt affect the git history.

Thank you!!

**Comment by avinal** [comment]
If you rebase to `upstream/main` you can avoid the merge. For a repository like this, you will rarely find a conflict in rebasing. And for squashing I generally prefer soft reset commits and then new commit for all the changes.

**Comment by soham4abc** [comment]
> If you rebase to `upstream/main` you can avoid the merge. For a repository like this, you will rarely find a conflict in rebasing. And for squashing I generally prefer soft reset commits and then new commit for all the changes.

sure sir I will keep that in mind from the next time!

Thank you for your input!! Will follow it now on!

**Pull request closed without merging**
