### PR TITLE
added codeql action

### PR DESCRIPTION
**Pull request by Ayush7614**
Signed-off-by: Ayush Kumar [ayushknj3@gmail.com](mailto:ayushknj3@@gmail.com)

## Project

ReactUI

### Changes

Added Codeql action for code analysis

### Notes

screenshot-github com-2022 06 05-00_29_01

All Checks are passed

### CODE REVIEW

**Comment by Ayush7614** [comment]
cc @GMishx

**Comment by GMishx** [comment]
@Ayush7614 Can you please explain the benefits of using CodeQL in this repository (where majority of files are markdown)?

Also, can you please remove comments from the workflow file? The are making it hard to understand the flow.

And please add license header to the new file.

**Comment by GMishx** [comment]
> @Ayush7614 Can you please explain the benefits of using CodeQL in this repository (where majority of files are markdown)?
> 
> Also, can you please remove comments from the workflow file? The are making it hard to understand the flow.
> 
> And please add license header to the new file.

Can you please act upon the suggestions @Ayush7614 ?

**Comment by Ayush7614** [comment]
> > @Ayush7614 Can you please explain the benefits of using CodeQL in this repository (where majority of files are markdown)?
> > Also, can you please remove comments from the workflow file? The are making it hard to understand the flow.
> > And please add license header to the new file.
> 
> Can you please act upon the suggestions @Ayush7614 ?

Sorry For Late Reply @GMishx 
In this repo CodeQL analysis for finding code vulnerabilities, yes i know majority of files are markdown but in this site we also use react , yarn and js. Markdown files are for information but at end whole website are designed from reactjs. so that`s why i uses this here

**Comment by GMishx** [comment]
> Sorry For Late Reply @GMishx In this repo CodeQL analysis for finding code vulnerabilities, yes i know majority of files are markdown but in this site we also use react , yarn and js. Markdown files are for information but at end whole website are designed from reactjs. so that`s why i uses this here

I don't think using something like CodeQL just for vulnerability analysis is a good thing. Code analysis only makes sense if you are generating any code (which we are not).

It might be helpful for other codebase like FOSSologyUI, atarashi, etc.

We are using a JS library, also a popular one, which themself will have some analysis tool. If there is any vulnerability reported on Docusaurus, it will be reported by GitHub's dependency analysis.

If anything, I will recommend to setup dependabot to update the dependencies. Please have a look at https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates

**Comment by GMishx** [comment]
As I was writing, I enabled dependabot and there are some open vulnerabilities in the dependencies (note, none of them were reported by codeql)

image

**Comment by GMishx** [comment]
Closing the PR as there are no updates.

Please reopen if needed.

**Pull request closed without merging**
